name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: false
          spec: |
            cypress/e2e/**/*.cy.js

      - name: Merge Mochawesome reports
        run: |
          npx mochawesome-merge reports/mochawesome/*.json > reports/mochawesome/merged.json
          npx marge reports/mochawesome/merged.json -f report -o reports/mochawesome/html

      - name: Upload Cypress videos, screenshots & HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
            reports/mochawesome/html

      - name: Display HTML report path
        run: echo "HTML report available at reports/mochawesome/html/report.html"
